@baseUrl=http://localhost:3333/v1
@host=http://localhost:3333

### Get the user 

GET {{baseUrl}}/profile

### Get all campaigns

GET {{baseUrl}}/campaigns

### Get one campaign

DELETE {{baseUrl}}/campaigns/1

### Get the wiki

GET {{baseUrl}}/wiki

### Get one wiki

DELETE  {{baseUrl}}/wiki/1

### Update or New wiki

PATCH {{baseUrl}}/wiki/8
Content-Type: application/json

{   
    "slug": "A",
    "title": "B",
    "full_title": "C",
    "type": "region"
}

### Create a new campaign

POST {{baseUrl}}/campaigns
Content-Type: application/json

{
    "campaign_name": "SUPER TEST",
    "description": "DIAMS SUPER LOL",
    "created_at": null,
    "user_id": 1
}
