@baseUrl=http://localhost:3333/v1
@host=http://localhost:3333

### Get the user 

GET {{baseUrl}}/profile

### Get all campaigns

GET {{baseUrl}}/campaigns

### Get one campaign

GET {{baseUrl}}/campaigns/2

### Get the wiki

GET {{baseUrl}}/wiki

### Get one wiki

DELETE  {{baseUrl}}/wiki/{*}

### Update or New wiki

PATCH {{baseUrl}}/wiki/4
Content-Type: application/json

{   
    "slug": "lol",
    "title": "prout",
    "full_title": "peut être vide",
    "type": "region"
}